
[build]
    # command = "npm run build"
    # publish = "/public"
    functions = "functions-build"

[[headers]]
    for = "/*"
        [headers.values]
            Access-Control-Allow-Origin = "*"